name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr_title:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "PR title: $TITLE"
